### ISSUE TITLE
Explain what the colors mean

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-protein-visualizer#11]
Display a link (or legend) explaining what the different colors in the viewer signify.

We would probably have to dig into `bio-pv` to find this information.
https://pv.readthedocs.io/en/v1.8.1/

**Comment by akshatbhargava123** [comment]
Hi @uosl , actually I couldn't find color significance on the pv docs page. Could you please have a look at this (https://www.rcsb.org/pages/help/3dview), the color scheme section if that helps.

**Comment by heralden** [comment]
Thanks for looking! The *By Element/CPK* color scheme is actually correct, and you can find a more exhaustive reference on [Wikipedia](https://en.wikipedia.org/wiki/CPK_coloring#Typical_assignments).

It seems the PV documentation also mentions this page, under `pv.color.uniform` which I assume is the default coloring.
https://pv.readthedocs.io/en/v1.8.1/coloring.html#available-color-operations

If you could take the table from Wikipedia, (just remove the third column, as having the color and the name of the gases should be enough) make it small and compact and perhaps put it at the bottom of the PV, it would make a great solution.

*PS: Rachel said it would be very useful to also support coloring by secondary structure. I'll create a new issue for this with more information, so don't worry about this now.*

**Comment by bistaastha** [comment]
@uosl @akshatbhargava123 Hi! Can I work on this?

**Comment by akshatbhargava123** [comment]
@bistaastha sure, that would really help!
