### ISSUE TITLE
Set default viewer mode correctly

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-protein-visualizer#12]
The view defaults to *cartoon* although the "Select Viewer Mode" dropdown is by default *spline*. This is confusing; we should have the dropdown show the actual default view *cartoon*.

**Comment by akshatbhargava123** [comment]
@uosl I think the pull request resolved the issue, please close if I'm not missing something.

**Comment by heralden** [comment]
Thanks! I forgot to close the issue.
