### ISSUE TITLE
Support more color operations

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-protein-visualizer#15]
Similar to how we let the user select *viewer mode*, we should also give the user a dropdown to select **color operations**.

https://pv.readthedocs.io/en/v1.8.1/coloring.html#available-color-operations

We can start by supporting two color operations:
- uniform (which is default now)
- by secondary structure

According to the documentation I linked above, you can change to *by secondary structure* by calling `pv.color.bySS()`, and change back to uniform with `pv.color.uniform()`.

When we have a color legend (#11) we will need to also update the legend based on the currently active color operation. For the new *by secondary structure* color operation, use the colors [listed in these 3 tables](http://jmol.sourceforge.net/jscolors/#Secondary%20structure).

**Comment by akshatbhargava123** [comment]
I'll work on this, assign to me please.

**Comment by heralden** [comment]
Thanks for picking this up! [=
