### ISSUE TITLE
Change protein selector to a dropdown

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/bluegenes-protein-visualizer#2]
Sometimes, when the gene has a lot of proteins, the height of the protein visualizer is too big in BlueGenes. It would be better to have a dropdown to select the protein and a text over it saying something like "Choose a protein to be visualized".

**Comment by AdrianBZG** [comment]
Screenshot of what happens (Gene: KRAS):

![image](https://user-images.githubusercontent.com/8275330/60508110-a0afae80-9cc1-11e9-8bff-b600f9cd8faf.png)

**Comment by yochannah** [comment]
what about a typeahead + dropdown, maybe? best of both worlds - you can
look for your preferred one or select it from a list

**Comment by AdrianBZG** [comment]
Sounds good!

**Comment by akshatbhargava123** [comment]
@yochannah just to confirm - by typeahead you mean input with search and results in dropdown?

**Comment by yochannah** [comment]
Something like this:
https://twitter.github.io/typeahead.js/examples/#default-suggestions
(doesn't have to be the same library though if another is better)

**Comment by akshatbhargava123** [comment]
Resolved, thanks for this awesome enhancement idea.
