### ISSUE TITLE
Change visualization depending whether it is a Gene or a Protein page

### ISSUE THREAD

**Issue by AdrianBZG** [intermine/bluegenes-protein-visualizer#7]
It would be nice to check in the tool if the current page is a Gene or a Protein page, and do the following:

- If it's a Gene page, just do the same thing that's currently doing.
- If it's a Protein page, just show the protein structure of the protein.

**Comment by akshatbhargava123** [comment]
Great idea to reuse the viz.
@AdrianBZG, what the tool will be receiving from BlueGenes in case of protein page - id or symbol?

**Comment by AdrianBZG** [comment]
Protein.id - as discussed in Discord
