### ISSUE TITLE
Handle null response to PdbQuery

### ISSUE THREAD

**Issue by heralden** [intermine/bluegenes-protein-visualizer#9]
Sometimes searching for the primaryAccession we receive from intermine doesn't return any results from RCSB's PDB, and the JVA will crash due to passing null data to pv. (The JVA will suddenly disappear while showing the loading indicators.)

Can we show a suitable message when PDB doesn't return any results?
Suggestion: *No results found for X in RCSB Protein Data Bank*

One protein ID without results you can test with is `20840312`.

**Comment by akshatbhargava123** [comment]
Thanks for the issue, while working on this I assumed it'll always return results (bad assumption :P)

Working on the same.
